### ISSUE TITLE
Refine exclusion process to recommend blocks of trials for exclusion

### ISSUE THREAD

**Issue by ezavitz** [ezavitz/processSpikingMoveStim#4]
One of the biggest issues is that the populations of neurons are not stable over the entire 4h duration of the recordings. Instead of dropping neurons who don't meet requirements for stationarity, instead define a set of "valid" trials for each cluster.

Brainstorming, here are some of the exclusion criteria that may work well: 

- [ ] Trials where Zsc > 2 are invalid for hyperactivity (seizure? cell dying?)
- [ ] Assume that clusters may or may not persist in time. To define trials where a cluster is present, analyse for each direction whether rates are consistent over time or not.
- [ ] There may be issues with an entire array/brain - look across channels for times when Zsc is high/low.

**Comment by nicholasprice** [comment]
I think it might be helpful to distinguish three types of badness:
1. Delta changes - isolated bad trials (e.g. electrical noise) 
2. Step changes - instantaneous changes in isolation (e.g. electrode failure)
3. Slow changes - isolations change over time (e.g. anaesthesia)
Type 3 are hard and will require defining thresholds, where we know we'll be throwing away potentially-usable data. 

We could log the subset of trials in which a neuron is considered valid, but then we'd need to be able to handle that in a pretty sophisticated way, e.g. tuning for some neurons might be based on all trials and for other neurons based on different subsets of trials. We'd also need to identify the set of trials in which all, or most, neurons were valid. 
This would need sensible limits such as a neuron can appear and disappear at most once within a file/session.

**Comment by nicholasprice** [comment]
Possible algorithms
1. Delta changes - identify trials in which mean-across-neurons Z-score exceeds a threshold
2. Step changes - for individual neurons, perform a sliding analysis averaging pre- and post- Z-scores. Any differences exceeding a threshold will identify a change-point. Ugh. So complicated. Plus the threshold would depend on the number of trials pre/post.
Step changes at population level?? 
4. Slow changes - do we do this at the population or the individual neuron level (or both!)

**Comment by ezavitz** [comment]
Try an approach where we test for visual responsiveness at different times
